#pragma once
#include "Hooks.h"
#include "Utils/recvproxyhook.h"
#include "Settings.h"	
#include "SDK\SDK.h"
#include "SDK\Definitions.h"
#include "SDK/materialconfig.h"
#include "Interfaces.h"
#include "Utils/Math.h"
#include "Hacks/AutoWall.h"
#include "Hacks/AimBot.h"


#include "Hacks/BunnyHop.h"
#include "Hacks/moonwalk.h"
#include "Hacks/AirStuck.h"
#include "Hacks/AntiAim.h"
#include "Hacks/AsusWalls.h"
#include "Hacks/AutoAccept.h"
#include "Hacks/AutoBlock.h"
#include "Hacks/AutoDefuse.h"
#include "Hacks/AutoStrafe.h"
#include "Hacks/nofog.h"

#include "Hacks/ClanTagChanger.h"
#include "Hacks/CustomGlow.h"
#include "Hacks/DLights.h"
#include "Hacks/EdgeJump.h"
#include "Hacks/Chams.h"
#include "Hacks/ESP.h"
#include "Hacks/FakeLag.h"
#include "Hacks/TriggerBot.h"
#include "Hacks/FOVChanger.h"
#include "Hacks/GrenadeHelper.h"
#include "Hacks/grenadeprediction.h"
#include "Hacks/HitMarkers.h"
#include "Hacks/JumpThrow.h"
#include "Hacks/NameChanger.h"
#include "Hacks/NameStealer.h"
#include "Hacks/NoFlash.h"
#include "Hacks/NoSky.h"
#include "Hacks/NoSmoke.h"
#include "Hacks/Noduckcooldown.h"

#include "Hacks/Radar.h" 
#include "Hacks/ShowSpectators.h"
#include "Hacks/RecoilCrosshair.h"
#include "Hacks/SniperCrosshair.h"
#include "Hacks/Resolver.h"
#include "Hacks/ShowRanks.h"
#include "Hacks/Spammer.h"

#include "Hacks/ThirdPerson.h"
#include "Hacks/View.h"
#include "SkinChanger.h"
#include "Hacks/PredictionSystem.h"
#include "Hacks/WalkBot.h"
#include "Hacks/Tracer.h"
#include "Hacks/FakeWalk.h"
#include "Utils/XorStr.hpp"
#include "Hacks/autoknife.h"

#include "Hacks/disablepostprocessing.h"
#include "Hacks/LobbyMod.h"
#include "Hacks/LagComp.h"
#include "Hacks/speedindicator.h"
#include "Hacks/lbyindicator.h"
#include "Hacks/angleindicator.h"
#include "Hacks/valvedscheck.h"

//Hooks
#include "modsupport.h"
#include "Shortcuts2.h"

//GUI
#include "GUI/Windows/resolverinfo.h"
#include "GUI/Windows/eventlogger.h"
#include "GUI/Windows/configs.h"
#include "GUI/Tabs/LobbyChanger.h"
#include "Hacks/ReportBot.h"

